import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'
import useSWR from 'swr'
import Book from '../components/Book'

// function to fetch a particular url and return the data as jason
const fetcher = url => fetch(url).then(r => r.json())

export default function Home() {
  // first param is the path of the api endpoint that will be fetched
  // second param is the fetcher function that should execute to get the data
  const { data, error } = useSWR('/api/books', fetcher)

  // if the api encounters an error, this will render
  if (error) {
    return <Main>
      Error!
    </Main>
  }

  // if the data has not been resolved yet, this renders
  if (!data) {
    return <Main>
      Loading...
    </Main>
  }

  // if the data comes back as expected, this returns
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        {/* <Book title='The Color Purple'></Book> */}
      </Main>
    </Container>
  )
}
